FROM python:3.12-slim

WORKDIR /app

COPY requirements.txt /app/requirements.txt
RUN pip install --no-cache-dir -r /app/requirements.txt

COPY rotator.py /app/rotator.py

CMD ["python", "/app/rotator.py"]
