FROM python:3.12-slim

WORKDIR /app

COPY requirements.txt /app/requirements.txt
RUN pip install --no-cache-dir -r /app/requirements.txt

COPY control_server.py /app/control_server.py

CMD ["python", "/app/control_server.py"]
